// Created on: 1997-10-08
// Created by: Olga KOULECHOVA
// Copyright (c) 1997-1999 Matra Datavision
// Copyright (c) 1999-2014 OPEN CASCADE SAS
//
// This file is part of Open CASCADE Technology software library.
//
// This library is free software; you can redistribute it and/or modify it under
// the terms of the GNU Lesser General Public License version 2.1 as published
// by the Free Software Foundation, with special exception defined in the file
// OCCT_LGPL_EXCEPTION.txt. Consult the file LICENSE_LGPL_21.txt included in OCCT
// distribution for complete text of the license and disclaimer of any warranty.
//
// Alternatively, this file may be used under the terms of Open CASCADE
// commercial license or contractual agreement.

#ifndef _BRepFeat_RibSlot_HeaderFile
#define _BRepFeat_RibSlot_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Handle.hxx>

#include <gp_Pnt.hxx>
#include <TopTools_DataMapOfShapeListOfShape.hxx>
#include <TopoDS_Shape.hxx>
#include <BRepFeat_PerfSelection.hxx>
#include <TopoDS_Wire.hxx>
#include <TopoDS_Face.hxx>
#include <TopTools_DataMapOfShapeShape.hxx>
#include <TopTools_ListOfShape.hxx>
#include <BRepFeat_StatusError.hxx>
#include <BRepBuilderAPI_MakeShape.hxx>
#include <Standard_Integer.hxx>
class TopoEdge;
class GeomPlane;
class Dir3d;
class GeomCurve3d;
class TopoVertex;
class LocOpe_Gluer;
class BRepAlgoAPI_BooleanOperation;

//! Provides functions to build mechanical features.
//! Mechanical features include ribs - protrusions and grooves (or slots) - depressions along
//! planar (linear) surfaces or revolution surfaces. The semantics of mechanical features is built
//! around giving thickness to a contour. This thickness can either be unilateral - on one side
//! of the contour - or bilateral - on both sides.
//! As in the semantics of form features, the thickness is defined by construction of shapes
//! in specific contexts. The development contexts differ, however,in case of mechanical features.
//! Here they include extrusion:
//! -   to a limiting face of the basis shape
//! -   to or from a limiting plane
//! -   to a height.
class BRepFeat_RibSlot : public BRepBuilderAPI_MakeShape
{
public:
  DEFINE_STANDARD_ALLOC

  //! Returns true if F a TopoShape of type edge or face has been deleted.
  Standard_EXPORT virtual Standard_Boolean IsDeleted(const TopoShape& F) Standard_OVERRIDE;

  //! Returns the list of generated Faces F. This list may be empty.
  Standard_EXPORT virtual const ShapeList& Modified(const TopoShape& F)
    Standard_OVERRIDE;

  //! Returns a list ShapeList of the faces S created in the shape.
  Standard_EXPORT virtual const ShapeList& Generated(const TopoShape& S)
    Standard_OVERRIDE;

  //! Returns the list  of shapes created  at the bottom  of
  //! the created form.  It may be an empty list.
  Standard_EXPORT const ShapeList& FirstShape() const;

  //! Returns  the list of shapes  created at the top of the
  //! created form.  It may be an empty list.
  Standard_EXPORT const ShapeList& LastShape() const;

  //! Returns a list of the limiting and glueing faces
  //! generated by the feature. These faces did not originally exist in the basis shape.
  //! The list provides the information necessary for
  //! subsequent addition of a draft to a face. It may be an empty list.
  //! If a face has tangent edges, no draft is possible, and the tangent edges must
  //! subsequently be removed if you want to add a draft to the face.
  Standard_EXPORT const ShapeList& FacesForDraft() const;

  //! Returns a list of the limiting and glueing edges
  //! generated by the feature. These edges did not originally exist in the basis shape.
  //! The list provides the information necessary for
  //! subsequent addition of fillets. It may be an empty list.
  Standard_EXPORT const ShapeList& NewEdges() const;

  //! Returns a list of the tangent edges among the
  //! limiting and glueing edges generated by the
  //! feature. These edges did not originally exist in
  //! the basis shape and are tangent to the face
  //! against which the feature is built.
  //! The list provides the information necessary for
  //! subsequent addition of fillets. It may be an empty list.
  //! If an edge is tangent, no fillet is possible, and
  //! the edge must subsequently be removed if you want to add a fillet.
  Standard_EXPORT const ShapeList& TgtEdges() const;

  Standard_EXPORT static Standard_Real IntPar(const Handle(GeomCurve3d)& C, const Point3d& P);

  Standard_EXPORT static TopoFace ChoiceOfFaces(ShapeList&     faces,
                                                   const Handle(GeomCurve3d)& cc,
                                                   const Standard_Real       par,
                                                   const Standard_Real       bnd,
                                                   const Handle(GeomPlane)& Pln);

  Standard_EXPORT BRepFeat_StatusError CurrentStatusError() const;

protected:
  //! Redefines the empty constructor.
  BRepFeat_RibSlot();

  //! General perform method...
  Standard_EXPORT void LFPerform();

  Standard_EXPORT Point3d CheckPoint(const TopoEdge&        e,
                                    const Standard_Real       bnd,
                                    const Handle(GeomPlane)& Pln);

  Standard_EXPORT Dir3d Normal(const TopoFace& F, const Point3d& P);

  Standard_EXPORT void EdgeExtention(TopoEdge&           e,
                                     const Standard_Real    bnd,
                                     const Standard_Boolean FirstLast);

  Standard_EXPORT Standard_Real HeightMax(const TopoShape& theSbase,
                                          const TopoShape& theSUntil,
                                          Point3d&             p1,
                                          Point3d&             p2);

  Standard_EXPORT Standard_Boolean ExtremeFaces(const Standard_Boolean    RevolRib,
                                                const Standard_Real       bnd,
                                                const Handle(GeomPlane)& Pln,
                                                TopoEdge&              FirstEdge,
                                                TopoEdge&              LastEdge,
                                                TopoFace&              FirstFace,
                                                TopoFace&              LastFace,
                                                TopoVertex&            FirstVertex,
                                                TopoVertex&            LastVertex,
                                                Standard_Boolean&         OnFirstFace,
                                                Standard_Boolean&         OnLastFace,
                                                Standard_Boolean&         PtOnFirstEdge,
                                                Standard_Boolean&         PtOnLastEdge,
                                                TopoEdge&              OnFirstEdge,
                                                TopoEdge&              OnLastEdge);

  Standard_EXPORT void PtOnEdgeVertex(const Standard_Boolean RevolRib,
                                      const TopoShape&    shape,
                                      const Point3d&          point,
                                      const TopoVertex&   FirstVertex,
                                      const TopoVertex&   LastVertex,
                                      Standard_Boolean&      PtOnEdge,
                                      TopoEdge&           OnEdge,
                                      Standard_Boolean&      PtOnVertex,
                                      TopoVertex&         OnVertex);

  Standard_EXPORT Standard_Boolean SlidingProfile(TopoFace&              Prof,
                                                  const Standard_Boolean    RevolRib,
                                                  const Standard_Real       myTol,
                                                  Standard_Integer&         Concavite,
                                                  const Handle(GeomPlane)& myPln,
                                                  const TopoFace&        BndFace,
                                                  const Point3d&             CheckPnt,
                                                  const TopoFace&        FirstFace,
                                                  const TopoFace&        LastFace,
                                                  const TopoVertex&      FirstVertex,
                                                  const TopoVertex&      LastVertex,
                                                  const TopoEdge&        FirstEdge,
                                                  const TopoEdge&        LastEdge);

  Standard_EXPORT Standard_Boolean NoSlidingProfile(TopoFace&              Prof,
                                                    const Standard_Boolean    RevolRib,
                                                    const Standard_Real       myTol,
                                                    Standard_Integer&         Concavite,
                                                    const Handle(GeomPlane)& myPln,
                                                    const Standard_Real       bnd,
                                                    const TopoFace&        BndFace,
                                                    const Point3d&             CheckPnt,
                                                    const TopoFace&        FirstFace,
                                                    const TopoFace&        LastFace,
                                                    const TopoVertex&      FirstVertex,
                                                    const TopoVertex&      LastVertex,
                                                    const TopoEdge&        FirstEdge,
                                                    const TopoEdge&        LastEdge,
                                                    const Standard_Boolean    OnFirstFace,
                                                    const Standard_Boolean    OnLastFace);

  //! Updates the data structures of descendant
  //! shapes during the glueing operation.Returns the modified, generated
  //! and deleted faces during the course of the glueing operation.
  Standard_EXPORT void UpdateDescendants(const LocOpe_Gluer& G);

  Standard_EXPORT void UpdateDescendants(const BRepAlgoAPI_BooleanOperation& aBOP,
                                         const TopoShape&                 SResult,
                                         const Standard_Boolean SkipFace = Standard_False);

  Point3d                             myFirstPnt;
  Point3d                             myLastPnt;
  Standard_Boolean                   myFuse;
  Standard_Boolean                   mySliding;
  TopTools_DataMapOfShapeListOfShape myMap;
  TopTools_DataMapOfShapeListOfShape myLFMap;
  TopoShape                       myFShape;
  TopoShape                       myLShape;
  BRepFeat_PerfSelection             myPerfSelection;
  TopoWire                        myWire;
  TopoShape                       mySbase;
  TopoFace                        mySkface;
  TopoFace                        myPbase;
  TopoShape                       myGShape;
  TopoShape                       mySUntil;
  TopTools_DataMapOfShapeShape       myGluedF;
  ShapeList               myNewEdges;
  ShapeList               myTgtEdges;
  ShapeList               myFacesForDraft;
  BRepFeat_StatusError               myStatusError;

private:
};

#include <BRepFeat_RibSlot.lxx>

#endif // _BRepFeat_RibSlot_HeaderFile
